(ns euler.clojure.problem2
  "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."
  )

(defn fibonacci-roof [n]
  ((fn [a n] (loop [a a n n]
             (let [b (apply + (drop (- (count a) 2) a))]
	             (if (> b n)
	               a
	               (recur (conj a b) n))))) 
    [1 2] n))

(defn fibonacci [n]
  (apply
    +
	  (filter
	    even?
		  (fibonacci-roof n))))

(print (fibonacci 4000000))